/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed-variant": "#004a77",
        "on-surface": "#191c1e",
        "on-error": "#ffffff",
        "surface-container": "#eceef0",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed": "#cfe5ff",
        "inverse-surface": "#2d3133",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b9c7e4",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#001d33",
        "background": "#f7f9fb",
        "surface": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "secondary-fixed": "#d7e2ff",
        "primary-fixed": "#d6e3ff",
        "outline-variant": "#c4c6d0",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-container": "#003370",
        "on-surface-variant": "#43474f",
        "on-secondary-fixed-variant": "#004491",
        "primary-fixed-dim": "#b9c7e4",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed-dim": "#acc7ff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#001a40",
        "on-tertiary-container": "#0099f0",
        "tertiary-container": "#002e4d",
        "secondary": "#115cb9",
        "on-primary-container": "#8693af",
        "surface-tint": "#515f78",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#0d1c32",
        "secondary-container": "#659dfe",
        "surface-bright": "#f7f9fb",
        "error": "#ba1a1a",
        "outline": "#747780",
        "tertiary-fixed-dim": "#98cbff",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dadc",
        "tertiary": "#00192d",
        "primary": "#08172d",
        "on-primary-fixed-variant": "#39475f",
        "primary-container": "#1e2c43"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "sans": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
